### PR TITLE
Package.json

### PR DESCRIPTION
**Pull request by AndalatuGH**

### CODE REVIEW

**Comment by ghost** [comment]
This is package code, and somebody elses project. It should be imported, rather than committed and tracked as if it's part of your project. If you didn't write it, do not commit it.

**Comment by ghost** [comment]
Write the code that uses bcrypt as part of the implementation of your application.

**Comment by ghost** [comment]
If you commit code like this, it's fair game for me to ask implementation details, perhaps to ask for a brief lecture on how jsdoc is working. Remember, you control the conversation of the presentation or interview based on what you bring up or commit.

**Review by Kendiya242 — CHANGES_REQUESTED** [review]
Hello Anda this is not the correct code for the hashing ticket. Even though you added bcrypt.js you have not connected the code with the backend.

**Pull request closed without merging**
