### PR TITLE
feat:create a budget form

### LINKED ISSUE #2: Basic Budget Form Functionality for Connecting to Backend with Priority Client-side Validations
Budget form includes:
a. Budget title
b. Brief description
c. Start date
d. End date
e. Total amount available
f. Category name with amount
g. Remaining amount shown to user at the end of creating the budget
h. Create budget button

### PR DESCRIPTION
**Pull request by Kendiya242**

### CODE REVIEW

**Review by dinaolmelak — APPROVED** [review]
LGTM

**Review by Scolin022 — CHANGES_REQUESTED** [review]
Well done, however, you still need to implement validation for the form data, that's the other half. 

A suggestion for the HTML file name, 
have a more specific naming for the files purpose, such as 
budgetCreation.html
or,
createBudget.html

But otherwise the HTML itself looks functional.
Good job!

**Comment by dinaolmelak** [comment]
@Scolin022 what would the JavaScript code validate?

**Comment by Kendiya242** [comment]
@Scolin022 I changed validation and the file naming convention. Please review the PR and your earliest convenience.

**Review by Scolin022 — APPROVED** [review]
Nice job! This works great for our MPV.

**Comment by Scolin022** [comment]
Due to public directory being removed, I created this branch again from the current develop and added the static files to the new appropriate folder for speedy development due to time constraints

**Review by Scolin022 — APPROVED** [review]
Looks good!

**Pull request merged**
