### PR TITLE
Info/about

### PR DESCRIPTION
**Pull request by AndalatuGH**
This page will contain the description of the finance app.

" FinanceApp, a TechWise Cohort II Project, is your all-in-one solution for effortless spending tracking and insightful financial analysis. With intuitive categorization, clear visualizations, and personalized budgeting features, it's never been easier to understand and manage your finances. Stay on top of your money wherever you go in real time. Take control of your financial future."

### CODE REVIEW

**Review by dinaolmelak — CHANGES_REQUESTED** [review]
Please make sure you are doing a PR to 'develop' And not to 'main'

**Comment by AndalatuGH** [comment]
> Please make sure you are doing a PR to 'develop' And not to 'main'

ok

**Comment by AndalatuGH** [comment]
ok

**Review by dinaolmelak — CHANGES_REQUESTED** [review]
Make sure to make a PR TOWARDS ~> `develop` branch

**Pull request closed without merging**
